
MARGIN_RIGHT = 20
MARGIN_LEFT = 20
MARGIN_TOP = 60
MARGIN_BOTTOM = 40

ROWS = 40
COLS = 40
BLOCK_WIDTH = 15
BLOCK_HEIGHT = BLOCK_WIDTH

SHAPE_NUM_COLS  = 5
SHAPE_NUM_ROWS = 5


XMAX = MARGIN_LEFT + COLS*BLOCK_WIDTH + MARGIN_RIGHT
YMAX = MARGIN_TOP +  ROWS*BLOCK_HEIGHT + MARGIN_BOTTOM


WHITE = [255,255,255]
BLACK = [0,0,0]
BROWN = [125,75,20]
LIGHTGRAY = [220,220,220]

CLR_BACKGROUND = WHITE
CLR_BOX = BROWN

FILE_SHAPES = 'shapes.txt'

